[package]
name = "lesson9_odds_and_ends"
version = "0.1.0"
authors = ["Javier Gutierrez <javier.guse@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
phrases = { path = "../Phrases" }
